shauno-buttons-rails/config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  resources :buttons, except: [:destroy]

  resources :reasons, except: [:edit, :update, :destroy]

  resources :developers, except: [:edit, :update, :destroy]

  resources :events, except: [:destroy]
end

shauno-buttons-rails/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :button
  belongs_to :reason
  belongs_to :developer

  validates :button_id, presence: true
  validates :timestamp, presence: true
  validates :developer_id, presence: true
  validates :reason_id, presence: true
end

shauno-buttons-rails/app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
        @button = Button.find(@event.button_id)
        @reason = Reason.find(@event.reason_id)
        @developer = Developer.find(@event.developer_id)
    end

    def new
        @event = Event.new
        
        @buttons = []
        buttons = Button.all
        buttons.each do |button|
            @buttons.push(button.uuid) # [button.uuid, button.id] can be used to put the id in the actual data, could be useful for the button addition form
        end
    end

    def create
        # need to do some magic to figure out the ids
        button = Button.find_by(uuid: params["event"]["uuid"])
        # byebug
        button_id = button.id
        reason_id = button.current_reason.id
        developer_id = button.current_developer.id

        params["event"]["button_id"] = button_id
        params["event"]["reason_id"] = reason_id
        params["event"]["developer_id"] = developer_id

        @event = Event.new(event_params)

        if @event.save
            redirect_to @event
        else
            render :new
        end
    end

    def edit
        update
    end

    def update
        @event = Event.find(params["id"])

        @event.update(to_ignore: true)

        @event.save

        redirect_to events_path
    end

    private
    def event_params
        params.require(:event).permit(:button_id, :timestamp, :reason_id, :developer_id)
    end
end

shauno-buttons-rails/app/helpers/events_helper.rb
module EventsHelper
end

shauno-buttons-rails/app/views/events/index.html.erb
<h1>All Events</h1>

<table>
<tr>
    <th>Button</th>
    <th>Timestamp</th>
    <th>Link</th>
</tr>
<% @events.each do |event| %>
    <% if !event.to_ignore %>
        <tr>
            <td><%= Button.find(event.button_id).uuid %></td>
            <td><%= event.timestamp %></td>
            <td><%= link_to "Show", event %></td>
        </tr>
    <% end %>
<% end %>
</table>

<%= link_to "New Event", new_event_path %>

shauno-buttons-rails/app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with model: @event do |form| %>
    
    <div>
        <%= form.label :uuid, "UUID of Button" %><br>
        <%= form.select :uuid, @buttons %>
    </div>

    <div>
        <%= form.label :timestamp, "Timestamp" %><br>
        <%= form.datetime_select :timestamp, include_seconds: true, date_separator: "-", time_separator: ":", datetime_separator: " ", use_month_numbers: true %>
    </div>

    <div>
        <%= form.submit %>
    </div>

<% end %>

shauno-buttons-rails/app/views/events/show.html.erb
<h1>Button "<%= @button.uuid %>" at <%= @event.timestamp %></h1>

<p>
    <strong>Reason: </strong><%= @reason.reason %>
    <br>
    <strong>Developer: </strong> <%= @developer.name %>
</p>

<%= link_to "Ignore this event", edit_event_path, data: {confirm: "Are you sure?"} %>
<br>
<%= link_to "Back to all events", events_path %>