shauno-buttons-rails/config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  resources :buttons, except: [:destroy]

  resources :reasons, except: [:edit, :update, :destroy]

  resources :developers, except: [:edit, :update, :destroy]

  resources :events, except: [:destroy]
end

shauno-buttons-rails/app/models/reason.rb
class Reason < ApplicationRecord
    has_many :button_reason
    has_many :button, through: :button_reason

    has_many :event

    validates :reason, presence: true
end

shauno-buttons-rails/app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
    def index
        @reasons = Reason.all
    end

    def show
        @reason = Reason.find(params["id"])
    end

    def new
        @reason = Reason.new
    end

    def create
        @reason = Reason.new(reasons_params)
        
        begin
            if @reason.save
                redirect_to @reason
            else
                render :new
            end
        rescue ActiveRecord::RecordNotUnique
            @reason.errors.add(:reason, message: "already exists!")
            render :new
        end
    end

    private
    def reasons_params
        params.require(:reason).permit(:reason)
    end
end

shauno-buttons-rails/app/helpers/reasons_helper.rb
module ReasonsHelper
end

shauno-buttons-rails/app/views/reasons/index.html.erb
<h1>All Reasons</h1>

<ul>
    <% @reasons.each do |reason| %>
        <li>
            <%= link_to reason.reason, reason %>
        </li>
    <% end %>
</ul>

<%= link_to "New Reason", new_reason_path %>

shauno-buttons-rails/app/views/reasons/new.html.erb
<h1>New Reason</h1>

<%= form_with model: @reason do |form| %>
    <div>
        <%= form.label :reason %>
        <%= form.text_field :reason %>
        <% if @reason.errors.any? %>
            <% @reason.errors.full_messages_for(:reason).each do |error| %>
                <div> <%= error %> </div>
            <% end %>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

shauno-buttons-rails/app/views/reasons/show.html.erb
<h1><%= @reason.reason %></h1>

<h3>Currently Associated Buttons</h3>
<table>
    <tr>
        <th>Button UUID</th>
        <th>Developer</th>
    </tr>

    <% @reason.button.where(button_reasons: { current: true }).each do |button| %>
        <tr>
            <td><%= link_to button.uuid, button %></td>
            <td><%= button.current_developer.name %></td> <%# need to turn this into a link once we've made the developer page %>
        </tr>
    <% end %>
</table>

<h3><%= link_to "Back to all reasons", reasons_path %></h3>