shauno-buttons-rails/config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  resources :buttons, except: [:destroy]

  resources :reasons, except: [:edit, :update, :destroy]

  resources :developers, except: [:edit, :update, :destroy]

  resources :events, except: [:destroy]
end

shauno-buttons-rails/app/models/developer.rb
class Developer < ApplicationRecord
    has_many :button_developer
    has_many :button, through: :button_developer

    has_many :event

    validates :name, presence: true
end

shauno-buttons-rails/app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
    def index
        @developers = Developer.all
    end

    def show
        @developer = Developer.find(params["id"])
    end

    def new
        @developer = Developer.new
    end

    def create
        @developer = Developer.new(developers_params)
        if @developer.save
            redirect_to @developer
        else
            render :new
        end
    end

    private
    def developers_params
        params.require(:developer).permit(:name)
    end
end

shauno-buttons-rails/app/helpers/developers_helper.rb
module DevelopersHelper
end

shauno-buttons-rails/app/views/developers/index.html.erb
<h1> Developers </h1>

<ul>
    <% @developers.each do |developer| %>
        <li>
            <%= link_to developer.name, developer %>
        </li>
    <% end %>
</ul>

<%= link_to "New Developer", new_developer_path %>

shauno-buttons-rails/app/views/developers/new.html.erb
<h1>New Developer</h1>

<%= form_with model: @developer do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
        <% if @developer.errors.any? %>
            <% @developer.errors.full_messages_for(:name).each do |error| %>
                <div> <%= error %> </div>
            <% end %>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

shauno-buttons-rails/app/views/developers/show.html.erb
<h1> <%= @developer.name %> </h1>

<h3>Currently Associated Buttons</h3>
<table>
    <tr>
        <th>Button UUID</th>
        <th>Reason</th>
    </tr>

    <% @developer.button.where(button_developers: { current: true }).each do |button| %>
        <tr>
            <td><%= link_to button.uuid, button %></td>
            <td><%= button.current_reason.reason %></td> <%# need to turn this into a link once we've made the developer page %>
        </tr>
    <% end %>
</table>