shauno-buttons-rails/config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  resources :buttons, except: [:destroy]

  resources :reasons, except: [:edit, :update, :destroy]

  resources :developers, except: [:edit, :update, :destroy]

  resources :events, except: [:destroy]
end

shauno-buttons-rails/app/models/button.rb
class Button < ApplicationRecord
    has_many :button_reason
    has_many :reason, through: :button_reason

    has_many :button_developer
    has_many :developer, through: :button_developer

    has_many :event

    validates :uuid, presence: true

    def current_reason
        self.reason.where(button_reasons: { current: true }).first
    end

    def current_developer
        self.developer.where(button_developers: { current: true }).first
    end
end

shauno-buttons-rails/app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController
    def index
        @buttons = Button.all
    end

    def show
        @button = Button.find(params[:id])
        @reason = @button.current_reason
        @developer = @button.current_developer
    end

    def new
        @button = Button.new

        create_instance_variables
    end

    def create
        @button = Button.new(button_params)
        
        begin
            if @button.save
                # need to set up the associations before redirecting

                new_reason_id = Reason.find_by(reason: params["button"]["reason"]).id
                join1 = ButtonReason.new(button_id: @button.id, reason_id: new_reason_id)
                join1.save

                new_developer_id = Developer.find_by(name: params["button"]["developer"]).id
                join2 = ButtonDeveloper.new(button_id: @button.id, developer_id: new_developer_id)
                join2.save

                redirect_to @button
            else
                create_instance_variables
                render :new
            end
        rescue ActiveRecord::RecordNotUnique
            @button.errors.add(:uuid, message: "already exists!")

            create_instance_variables
            render :new
        end
    end

    def edit
        @button = Button.find(params[:id])
        @reason = @button.current_reason
        @developer = @button.current_developer

        create_instance_variables
    end

    def update
        @button = Button.find(params[:id])
        
        if @button.update(button_params)
            if @button.current_reason.reason != params["button"]["reason"] #if reason thats been given is not the one alr assigned to it
                ButtonReason.where(button_id: @button.id).update(current: false)
            
                new_reason_id = Reason.find_by(reason: params["button"]["reason"]).id
                reason = ButtonReason.new(button_id: @button.id, reason_id: new_reason_id)
                reason.save
            end

            if @button.current_developer.name != params["button"]["developer"]
                ButtonDeveloper.where(button_id: @button.id).update(current: false) 

                new_developer_id = Developer.find_by(name: params["button"]["developer"]).id
                developer = ButtonDeveloper.new(button_id: @button.id, developer_id: new_developer_id)
                developer.save
            end

            redirect_to @button
        else
            create_instance_variables
            @reason = @button.current_reason
            @developer = @button.current_developer

            render :edit
        end
    end

    private
    def button_params
        params.require(:button).permit(:uuid, :is_active)
    end

    def create_instance_variables
        reasons = Reason.all
        @reasons = []
        reasons.each do |reason|
            @reasons.push(reason.reason)
        end

        developers = Developer.all
        @developers = []
        developers.each do |developer|
            @developers.push(developer.name)
        end
    end
end

shauno-buttons-rails/app/helpers/buttons_helper.rb
module ButtonsHelper
end

shauno-buttons-rails/app/views/buttons/edit.html.erb
<h1>Edit Button</h1>

<%# <%= render "form", button: @button, reasons: @reasons, reason: @reason, developers: @developers, developer: @developer %> 

<%= form_with model: @button do |form| %>
    <div>
        <%= form.label :is_active, "Button is inactive" %>: 
        <%= form.check_box :is_active, { checked: !@button.is_active }, false, true %>
    </div>

    <div>
        <%= form.label :reason %><br>
        <%= form.select :reason, @reasons, selected: @reason.reason %>
    </div>

    <div>
        <%= form.label :developer %><br>
        <%= form.select :developer, @developers, selected: @developer.name %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

shauno-buttons-rails/app/views/buttons/index.html.erb
<h1>All Buttons</h1>

<h3>Active buttons</h3>
<ul>
<% @buttons.each do |button| %>
    <% if button.is_active %>
        <li>
            <%= link_to button.uuid, button %>
        </li>
    <% end %>
<% end %>
</ul>

<h3>Inactive buttons</h3>
<ul>
<% @buttons.each do |button| %>
    <% if !button.is_active %>
        <li>
            <%= link_to button.uuid, button %>
        </li>
    <% end %>
<% end %>
</ul>

<%= link_to "New Button", new_button_path %>

shauno-buttons-rails/app/views/buttons/new.html.erb
<h1>New Button</h1>

<%= form_with model: @button do |form| %>
    <div>
        <%= form.label :uuid %><br>
        <%= form.text_field :uuid %>
        <% if @button.errors.any? %>
            <% @button.errors.full_messages_for(:uuid).each do |error| %>
                <div> <%= error %> </div>
            <% end %>
        <% end %>
    </div>

    <div>
        <%= form.label :is_active, "Button is inactive" %>: 
        <%= form.check_box :is_active, { checked: false }, false, true %>
    </div>

    <div>
        <%= form.label :reason %><br>
        <%= form.select :reason, @reasons %>
    </div>

    <div>
        <%= form.label :developer %><br>
        <%= form.select :developer, @developers %>
    </div>

    <div>
        <%= form.submit %>
    </div>

<% end %>

shauno-buttons-rails/app/views/buttons/show.html.erb
<h1>Button number <%= @button.id %></h1>

<p>
    <strong>UUID: </strong><%= @button.uuid %>
    <br>
    <strong>Is active: </strong><%= @button.is_active %>
</p>
<p>
    <strong>Associated reason: </strong><%= @reason.reason %>
    <br>
    <strong>Associated developer: </strong><%= @developer.name %>
</p>

<h4><%= link_to "Edit", edit_button_path(@button) %></h4>
<h4><%= link_to "Back to all buttons", buttons_path %></h4>